// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyaimtirhbxtczihruxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5YWltdGlyaGJ4dGN6aWhydXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzA2MzMsImV4cCI6MjA2MzIwNjYzM30.Cc8GFUICJTx7o7d7SU6tyEkKJxehrWtBh-DA5ksF60c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);